/**
 * Overseer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Enum containing types of machines available in the system
 */
export type MachineType = 'cpu' | 'gpu';

export const MachineType = {
    Cpu: 'cpu' as MachineType,
    Gpu: 'gpu' as MachineType
};