/**
 * Overseer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IpAddress } from './ipAddress';
import { Machines } from './machines';
import { Resources } from './resources';

/**
 * Describes a single server with resources and machines running on it
 */
export interface Server { 
    name: string;
    address: IpAddress;
    running: Machines;
    free: Machines;
    resources: Resources;
}