/**
 * Overseer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IpAddress } from './ipAddress';
import { MachineType } from './machineType';
import { SessionStatus } from './sessionStatus';

/**
 * Contains information about single session. Address is sent only if session is ready
 */
export interface Session { 
    id: string;
    type: MachineType;
    status: SessionStatus;
    address?: IpAddress;
}