/**
 * Overseer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Status of the session
 */
export type SessionStatus = 'Ready' | 'Pending' | 'Cancelled';

export const SessionStatus = {
    Ready: 'Ready' as SessionStatus,
    Pending: 'Pending' as SessionStatus,
    Cancelled: 'Cancelled' as SessionStatus
};