/**
 * Overseer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Resources } from './resources';
import { Server } from './server';

/**
 * Object containing information about resources for admin application
 */
export interface TotalResources { 
    servers: Array<Server>;
    total: Resources;
}