/*
 * Overseer
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using OneClickDesktop.Api.Attributes;
using OneClickDesktop.Api.Models;

namespace OneClickDesktop.Api.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class LoginApiController : ControllerBase
    { 
        /// <summary>
        /// Log into system
        /// </summary>
        /// <param name="login">Used to send login information</param>
        /// <response code="200">Response containing token for authorization after successful login</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="0">Generic error</response>
        [HttpPost]
        [Route("/login")]
        [Consumes("application/json")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(Token))]
        [ProducesResponseType(statusCode: 401, type: typeof(Error))]
        [ProducesResponseType(statusCode: 0, type: typeof(Error))]
        public abstract IActionResult Login([FromBody]Login login);
    }
}
