/*
 * Overseer
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using OneClickDesktop.Api.Attributes;
using OneClickDesktop.Api.Models;

namespace OneClickDesktop.Api.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class MachinesApiController : ControllerBase
    { 
        /// <summary>
        /// Get number of available machines grouped into types
        /// </summary>
        /// <response code="200">Response containing types and amounts of available machines</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="0">Generic error</response>
        [HttpGet]
        [Route("/machines")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(List<Machine>))]
        [ProducesResponseType(statusCode: 401, type: typeof(Error))]
        [ProducesResponseType(statusCode: 0, type: typeof(Error))]
        public abstract IActionResult GetMachines();
    }
}
