name: Nuget Publish

on:
  push:
    branches:
      - main

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.x"
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - name: Setup Openapi Generator
        run: npm install @openapitools/openapi-generator-cli -g
      - name: Generate serverside api
        run: bash ./generate/nuget.sh
      - name: Build and pack library to nuget
        run: dotnet pack
        working-directory: ./nuget/src/OneClickDesktop.Api
      - name: Push nuget to nuget.org
        run: dotnet nuget push "bin/Release/OctocatApp.*.nupkg" --api-key ${{ secrets.NUGET_TOKEN }} --source "github"
        working-directory: ./nuget/src/OneClickDesktop.Api
