name: OpenAPI Check

on:
  pull_request:
    branches:
      - main

jobs:
  validateAPI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Find modified files
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: " "
      - name: Check if API version changed
        run: bash ./check-version.sh
        env:
          BRANCH: ${{ github.base_ref }}
          MODIFIED: ${{ steps.file_changes.outputs.files_modified }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - name: Setup OpenAPI validator
        run: npm install @openapitools/openapi-generator-cli -g
      - name: Validate Schema
        run: openapi-generator-cli validate -i overseer.yaml
