name: OpenAPI Check

on:
  pull_request:
    branches:
      - main

jobs:
  validateAPI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash ./check-version.sh
        env:
          BRANCH: ${{ github.base_ref }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - name: Setup OpenAPI validator
        run: npm install @openapitools/openapi-generator-cli -g
      - name: Validate Schema
        run: openapi-generator-cli validate -i overseer.yaml
